### ISSUE TITLE
Document host module parameter compute_attributes parameter with volumes_attributes

### ISSUE THREAD

**Issue by lucab85** [RedHatSatellite/satellite-ansible-collection#36] opened 2021-10-22 11:24 UTC
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Extend documentation of module `redhat.satellite.host` about parameter `compute_attributes` parameter with `volumes_attributes`.

The module support `volumes_attributes` as I could see in line numer 500 of  plugins/modules/host.py#
https://github.com/RedHatSatellite/satellite-ansible-collection/blob/998fd25e31259af44f4db0055689d60b655d4af3/plugins/modules/host.py#L500

I found only this usage under `compute_profile.yml` test:
https://github.com/RedHatSatellite/satellite-ansible-collection/blob/998fd25e31259af44f4db0055689d60b655d4af3/tests/test_playbooks/vars/compute_profile.yml#L21

**Comment by evgeni** [comment] 2021-11-02 08:08
This is a duplicate of https://bugzilla.redhat.com/show_bug.cgi?id=1945163

**Closed by evgeni** 2021-11-02 08:08 UTC
